# Release a new TW Blue installer on github.
# This workflow runs on push.
name: Release
on: [push, workflow_dispatch]
jobs:
  build:
  # Builds an x64 binary and an installer of TW Blue.
    runs-on: windows-2019
    steps:
      - name: clone repo
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Get python interpreter
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install python packages
        run: python -m pip install -r requirements.txt

      - name: Get nsis
        run: |
          iwr -useb get.scoop.sh -outfile 'install.ps1'
          .\install.ps1 -RunAsAdmin
          scoop update
          scoop bucket add extras
          scoop install nsis

      - name: Build binary
        run: |
          .\scripts\build.ps1
          mv src/dist scripts\TWBlue64

      - name: make installer
        run: |
          cd src
          python write_version_data.py
          cd ../scripts
          makensis twblue.nsi

      - name: Create new release
        run: gh release create snapshot -n "This release is a snapshot of the current development version of twblue." -p -t "Snapshot" scripts\TWBlue_setup.exe
