# Release a new TW Blue installer on github.
# This workflow runs on push.
name: Release
on: [push, workflow_dispatch]
jobs:
  build-x64-binary:
    runs-on: windows-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Get python interpreter
        uses: actions/setup-python@v4
      - name: get pip requirements
        run: pip install -r requirements.txt
      - name: Build binary
        run: |
          cd docs
          python documentation_importer.py
          python generator.py
          mv documentation ..\src\documentation
          cd ..
          cp license.txt src/documentation/license.txt
          cd src
          python setup.py build
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: TWBlue
          path: src/dist
