name: Release
on: [push, workflow_dispatch]
jobs:
  build-pillow:
    runs-on: windows-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Get python interpreter
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: x86

      - name: Build binary
        run: python -m pip install pillow
