# Release a new TW Blue installer on github.
# This workflow runs on push.
name: Release
on:
  push:
    tags: ["release"]
  workflow_dispatch:

jobs:
  build:
  # Builds an x64 binary and an installer of TW Blue.
    runs-on: windows-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Get python interpreter
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install python packages
        run: python -m pip install -r requirements.txt

      # - name: Get nsis
      #   run: |
      #     iwr -useb get.scoop.sh -outfile 'install.ps1'
      #     .\install.ps1 -RunAsAdmin
      #     scoop update
      #     scoop bucket add extras
      #     scoop install nsis

      - name: Build binary
        run: |
          .\scripts\build.ps1
          mv src/dist scripts\TWBlue64

      - name: make installer
        run: |
          cd scripts
          makensis twblue.nsi

      - name: Create new release
        env:
          gh_token: ${{ github.token }}
        run: |
          mkdir .release-assets
          ls scripts
          mv scripts\TWBlue_setup.exe .release-assets\TWBlue_setup_$(cat version.txt).exe
          7z a -tzip .release-assets\TWBlue_portable_$(cat version.txt).zip scripts\TWBlue64
          gh release create release -p -t "Version $(cat version.txt)" .github-releases\*
